### ISSUE TITLE
this still work?

### ISSUE THREAD

**Issue by jko64** [rand0mgh/subrock-dl-gui#1]
There are still some subrocks forks up (as of feb 8 2022), would this work on them?

**Comment by Kaisiece** [comment]
iirc it will work if the fork havent changed the video folder location

**Comment by jko64** [comment]
> iirc it will work if the fork havent changed the video folder location

SO I CAN USE IT ON CATCOPTERTUBE??PRO

**Comment by rand0mgh** [comment]
As I said via Gitlab, which I plan to use mostly instead:
> I may make a new version allowing you to change SR forks via another text box soon.
This version will be coming soon.

**Comment by rand0mgh** [comment]
Update: You can find V2 [here](https://gitlab.com/rand0mgh/subrock-dl-gui)
